# QA APK Test Automation - Hybrid Docker Compose  
# Framework in container + Host emulator (cleanest setup)
# QA can watch tests run on their visible emulator screen

version: '3.8'

services:
  qa-automation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: qa-automation
    volumes:
      # Mount test results and screenshots to host
      - ../test-results:/app/test-results
      - ../screenshots:/app/screenshots
      - ../logs:/app/logs
      # Mount APK from host
      - ../app.apk:/app/app.apk:ro
      # Mount features for easy editing
      - ../features:/app/features
    ports:
      - "4723:4723"
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    # Connect to host network to reach emulator
    network_mode: "host"
    command: ["sh", "-c", "sleep 5 && npm test"]
    depends_on:
      - appium-server

  appium-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: appium-server
    ports:
      - "4723:4723"
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    network_mode: "host"
    command: ["npm", "run", "appium"]